# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bcfoverparRcppClean <- function(y_, z_, x_con_, x_mod_, x_mod_est_, x_con_info_list, x_mod_info_list, random_des, random_var, random_var_ix, random_var_df, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, con_sd, mod_sd, con_alpha, con_beta, mod_alpha, mod_beta, treef_name_, status_interval = 100L, RJ = FALSE, use_mscale = TRUE, use_bscale = TRUE, b_half_normal = TRUE, trt_init = 1.0) {
    .Call('_bcf_bcfoverparRcppClean', PACKAGE = 'bcf', y_, z_, x_con_, x_mod_, x_mod_est_, x_con_info_list, x_mod_info_list, random_des, random_var, random_var_ix, random_var_df, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, con_sd, mod_sd, con_alpha, con_beta, mod_alpha, mod_beta, treef_name_, status_interval, RJ, use_mscale, use_bscale, b_half_normal, trt_init)
}

bcfoverparRcppClean_ini <- function(ini_bcf, treedraws_con, treedraws_mod, muscale_ini, bscale0_ini, bscale1_ini, sigma_ini, pi_con_tau, pi_con_sigma, pi_mod_tau, pi_mod_sigma, mod_tree_scaling, y_, z_, x_con_, x_mod_, x_mod_est_, x_con_info_list, x_mod_info_list, random_des, random_var, random_var_ix, random_var_df, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, con_sd, mod_sd, con_alpha, con_beta, mod_alpha, mod_beta, treef_name_, status_interval = 100L, RJ = FALSE, use_mscale = TRUE, use_bscale = TRUE, b_half_normal = TRUE, update_mu_loading_tree = FALSE, trt_init = 1.0) {
    .Call('_bcf_bcfoverparRcppClean_ini', PACKAGE = 'bcf', ini_bcf, treedraws_con, treedraws_mod, muscale_ini, bscale0_ini, bscale1_ini, sigma_ini, pi_con_tau, pi_con_sigma, pi_mod_tau, pi_mod_sigma, mod_tree_scaling, y_, z_, x_con_, x_mod_, x_mod_est_, x_con_info_list, x_mod_info_list, random_des, random_var, random_var_ix, random_var_df, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, con_sd, mod_sd, con_alpha, con_beta, mod_alpha, mod_beta, treef_name_, status_interval, RJ, use_mscale, use_bscale, b_half_normal, update_mu_loading_tree, trt_init)
}

